# Generated by Django 4.2.2 on 2025-08-04 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_rename_updated_transaction_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reciver',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reciver_account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_account', to='account.account'),
        ),
    ]
