# Generated by Django 4.2.2 on 2025-08-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_transaction_reciver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsgoal',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Emergency Fund', 'Emergency Fund'), ('Education', 'Education'), ('Investment', 'Investment'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.DeleteModel(
            name='GoalTransaction',
        ),
    ]
