# Generated by Django 5.2.4 on 2025-08-07 01:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transaction_anomaly_reason_transaction_anomaly_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='authentication_method',
            field=models.CharField(default='PIN', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_type',
            field=models.CharField(default='Visa', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='device_type',
            field=models.CharField(default='Mobile', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='failed_transaction_count_7d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.CharField(default='Accra', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant_category',
            field=models.CharField(default='Groceries', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='anomaly_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='update',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
