# Generated by Django 5.2.4 on 2025-08-07 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transaction_authentication_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='is_anomalous',
            new_name='ip_flag',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='is_weekend',
            new_name='previous_fraud_activity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='anomaly_reason',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='anomaly_score',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='authentication_method',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='failed_transaction_count_7d',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='location',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='merchant_category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_distance',
        ),
    ]
