# Generated by Django 5.2.4 on 2025-08-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_is_anomalous_transaction_ip_flag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='previous_fraud_activity',
            new_name='previous_fraudulent_activity',
        ),
    ]
