# Generated by Django 5.2.4 on 2025-08-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_previous_fraud_activity_transaction_previous_fraudulent_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='authentication_method',
            field=models.CharField(default='PIN', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_type',
            field=models.CharField(default='Visa', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='daily_txn_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='device_type',
            field=models.CharField(default='Mobile', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='failed_transaction_count_7d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.CharField(default='Accra', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant_category',
            field=models.CharField(default='Groceries', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_distance',
            field=models.FloatField(default=0.0),
        ),
    ]
