# Generated by Django 5.2.4 on 2025-08-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_transaction_authentication_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='avg_txn_amount_7d',
            field=models.FloatField(default=0.0),
        ),
    ]
