# Generated by Django 5.2.4 on 2025-08-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_transaction_avg_txn_amount_7d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ip_flag',
        ),
        migrations.AddField(
            model_name='transaction',
            name='anomaly_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='anomaly_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_anomalous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='Online', max_length=100),
        ),
    ]
