# Generated by Django 5.2.4 on 2025-08-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_transaction_ip_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ip_flag',
            field=models.BooleanField(default=False),
        ),
    ]
