# Generated by Django 5.2.4 on 2025-08-07 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_transaction_ip_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_distance',
            new_name='txn_distance',
        ),
    ]
