# Generated by Django 5.2.4 on 2025-08-07 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_transaction_distance_transaction_txn_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='failed_transaction_count_7d',
            new_name='failed_txn_count_7d',
        ),
    ]
