# Generated by Django 5.2.4 on 2025-08-07 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_failed_transaction_count_7d_transaction_failed_txn_count_7d'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='authentication_method',
            new_name='auth_method',
        ),
    ]
